In [1]:
import os
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import joblib
from matplotlib.colors import ListedColormap

plt.style.use("fivethirtyeight")


In [2]:
class Perceptron:
    def __init__(self,eta:float = None,epochs:int=None):
        self.weights = np.random.randn(3) * 1e-4 #small random weights
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f"initial weight before training \n{self.weights}")
        self.eta=eta
        self.epochs=epochs
    
    def _z_outcome(self,inputs,weights):
        return np.dot(inputs,weights)
    
    def activation_function(self,z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, X, y):
        self.X=X
        self.y=y
        
        X_with_bias = np.c_[self.X,-np.ones((len(self.X),1))]
        print(f"X_with_bias \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("__"*10)
            print(f"for epoch >> {epoch + 1}")
            print("__"*10)
            
            z = self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error : \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
            print(f"updated weights after epoch : {epoch}/{self.epochs}: \n{self.weights}")
            print("##"*10)
    
    def predict(self, X):
        X_with_bias = np.c_[X,-np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)
        
    
    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"\ntotal loss: {total_loss}\n")
        return total_loss
    
    def _create_directory(self, model_dir, filename):
        os.mkdir(model_dir)
        return os.path.join(model_dir, filename)
    
    def save(self, filename, model_dir=None):
        if model_dir:
            model_file_path = self._create_directory(model_dir, filename)
            joblib.dump(self, model_file_path)
        else:
            model_file_path = self._create_directory("model", filename)
            joblib.dump(self, model_file_path)
    
    def load(self,filepath):
        return joblib.load(filepath) 
        
        
        

In [3]:
def prepare_data(df,target_col):
    X = df.drop(target_col,axis=1)
    
    y = df[target_col]
    
    return X,y

In [4]:
AND = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y" :[0,0,0,1]
}

df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [5]:
X, y = prepare_data(df_AND,"y")

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA,epochs=EPOCHS)
model_and.fit(X,y)
_ = model_and.total_loss()

initial weight before training 
[-5.49430662e-05 -7.70082229e-05 -1.00879668e-04]
X_with_bias 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
____________________
for epoch >> 1
____________________
predicted value after forward pass: 
[1 1 1 0]
error : 
0   -1
1   -1
2   -1
3    1
Name: y, dtype: int64
updated weights after epoch : 0/10: 
[-5.49430662e-05 -7.70082229e-05  1.99899120e-01]
####################
____________________
for epoch >> 2
____________________
predicted value after forward pass: 
[0 0 0 0]
error : 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch : 1/10: 
[0.09994506 0.09992299 0.09989912]
####################
____________________
for epoch >> 3
____________________
predicted value after forward pass: 
[0 1 1 1]
error : 
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch : 2/10: 
[-5.49430662e-05 -7.70082229e-05  2.99899120e-01]
####################
____________________
for epoch >> 4
__________

In [6]:
model_and.save("and_model")

In [7]:
from platform import python_version

print(python_version())

3.9.7


In [8]:
reload_and = Perceptron()

In [9]:
reload_and_model=reload_and.load(filepath = "model/and_model")

In [10]:
reload_and_model.predict(X=[[1,1]])

array([1])

In [11]:
reload_and_model.predict(X=[[1,0]])

array([0])

In [12]:
reload_and_model.predict(X=[[0,0]])

array([0])

In [13]:
reload_and_model.predict(X=[[0,1]])

array([0])

In [10]:
class hello:
    def __init__(self, name):
        self.name = name
        
    def set(self,title):
        self.title = title
        
    def print_(self):
        print(str(self.name + self.title))

In [11]:
bh=hello("chintu")

In [12]:
bh.__dict__

{'name': 'chintu'}

In [6]:
hello.__dict__

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.hello.__init__(self, name)>,
              'set': <function __main__.hello.set(self, title)>,
              'print_': <function __main__.hello.print_(self)>,
              '__dict__': <attribute '__dict__' of 'hello' objects>,
              '__weakref__': <attribute '__weakref__' of 'hello' objects>,
              '__doc__': None})

In [7]:
bh.set("bhoi")

In [8]:
hello.__dict__

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.hello.__init__(self, name)>,
              'set': <function __main__.hello.set(self, title)>,
              'print_': <function __main__.hello.print_(self)>,
              '__dict__': <attribute '__dict__' of 'hello' objects>,
              '__weakref__': <attribute '__weakref__' of 'hello' objects>,
              '__doc__': None})

In [9]:
bh.__dict__

{'name': 'chintu', 'title': 'bhoi'}